# Generated by Django 3.0.7 on 2020-07-22 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
