# Generated by Django 3.0.7 on 2020-07-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_author_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
